### ISSUE TITLE
Meta Tags adding in the same html.index file

### ISSUE THREAD

**Issue by Umar-Khan-Yousafzai** [Eng-Mouaz-M-AlShahmeh/meta_seo#1]
Hi there!
First of all, thank you very much for developing such a wonderful package. I was playing with this package and I am using go_router when I discovered this suspected issue.

For a little bit background of the issue:

1) I have created a new flutter project, add 2 packages (Meta_Seo & GO_ROUTER)
2) I added two stateful screens (Main Screen, Screen 2)
3) Now When I navigate from one screen to another screen, the meta tags are added again and again in the same index.html file.

Eg:

When I route to Screen 2, the meta tags from screen 2 are added to index.html and when I route back from screen 2 to main screen. The meta tags of main screen are added (again) in the html file.

![image](https://user-images.githubusercontent.com/43144366/201024120-e4b129f2-9a92-49a8-b629-2055cb793da5.png)

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thank you for your feedback, I am working on auto dispose MetaSEO version will published soon.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
The updated version is already published. Greetings,
