### ISSUE TITLE
Question regarding Async loading

### ISSUE THREAD

**Issue by MattyBoy4444** [Eng-Mouaz-M-AlShahmeh/meta_seo#10]
Before I go to all the trouble.  I am wondering if this will work when using async calls to load data that will then be used to set the ogTitle, ogDescription, etc.....?

EX: ID of data is provided to StatefullWidget.  Build runs with progress bar.  After data is retrieved, the meta tags are then set.  I am suspecting Facebook/Twitter aren't going to wait around for the values to be updated.

Anyone have experience with this?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thank you for your interest.. Most of the archiving platforms depend on the code coming from the server side (Server Side Rendering) SSR and not from Javascript Dom.. And the matter is not related to concurrency or not.. This is the reason and we are working to find a solution out of the box to solve the issue.. and the matter may take some time...

**Comment by MattyBoy4444** [comment]
K. Thanks

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Welcome

**Comment by agelospanagiotakis** [comment]
this is a major issue with flutter web applications :(
as you said 
"Facebook/Twitter aren't going to wait around for the values to be updated"

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for all support. Now I am updating the package with "Service Worker" to support SSR/SSG functions.

**Comment by mindfreak269** [comment]
any update for this case?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
There is a solution to the issue using service workers but it collides with the one in Flutter and work is still in progress to find an out-of-the-box solution...
