### ISSUE TITLE
seoNameJS - method not found

### ISSUE THREAD

**Issue by Dassine** [Eng-Mouaz-M-AlShahmeh/meta_seo#11]
I'm using for the first time meta_seo package but calling `meta.auth()` is crashing the web app: 

> Restarted application in 157ms.
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following NoSuchMethodError was thrown building HomePage(dirty, dependencies:
> [_LocalizationsScope-[GlobalKey#6ee74]]):
> 'seoNameJS'
> method not found
> Receiver: Instance of 'Window'
> Arguments: ["author", "Eng Mouaz M AlShahmeh"]
> 
> The relevant error-causing widget was:
>   HomePage
>   HomePage:file:///Users/liliadassinebelaid/DALIBEL/IDEAS/ProjectX/Titis%20-%20ParentConnect/Flutter/titis/lib/main.dart:107:22
> 
> When the exception was thrown, this was the stack:
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
> dart-sdk/lib/_internal/js_dev_runtime/patch/js_patch.dart 143:7               callMethod
>

Can you please help with this.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
give the full usage code of meta_seo with screenshots

**Comment by Dassine** [comment]
@Eng-Mouaz-M-AlShahmeh 


Here my main.dart: 

> void main() async {
>   if (!kIsWeb) {
>     MetaSEO().config();
>     WidgetsFlutterBinding.ensureInitialized();
>     await Firebase.initializeApp();
>   } else {
>     await Firebase.initializeApp(
>       options: DefaultFirebaseOptions.currentPlatform,
>     );
>   }
> 
>   runApp(const MyApp());
> }

and the page that crashes: 

> class HomePage extends StatelessWidget {
>   static const String name = 'home';
> 
>   const HomePage({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     setUserLanguage(AppLocalizations.of(context)!.localeCode);
> 
>     // Add MetaSEO just into Web platform condition
>     if (kIsWeb) {
>       // Define MetaSEO object
>       MetaSEO meta = MetaSEO();
>       // Add meta seo data for web app as you want
>       meta.author(author: 'Eng Mouaz M AlShahmeh');
>       // meta.description(description: 'Meta SEO Web Example');
>       // meta.keywords(keywords: 'Flutter, Dart, SEO, Meta, Web');
>     }
> 
>     return Scaffold(
>

**Comment by Dassine** [comment]
@Eng-Mouaz-M-AlShahmeh  it's not just auth(), it's any function of meta

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
I understand you feel there are errors, and many developers feel same, and fast they discover if you the MetaSEO().config(); condition. the package runs well without SSR support until the latest version of 3.0.7 and supports only JS Dom... etc

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for interest, @Dassine

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
I am workin now to product similar to react-helmet, and this may take some time, Thanks again,

**Comment by Dassine** [comment]
@Eng-Mouaz-M-AlShahmeh They are errors! What do you suggest? To remove `MetaSEO().config();`?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
refer the Readme.md file if you want.

**Comment by Dassine** [comment]
Not helpful. I will use something else.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Sure, as I mention before the work not completed yet at SSR,

**Comment by jeanbatm** [comment]
It is `if (kIsWeb)`, not `if (!kIsWeb)`
