### ISSUE TITLE
Unrecognized in Seo checker

### ISSUE THREAD

**Issue by TimBaumgart** [Eng-Mouaz-M-AlShahmeh/meta_seo#14]
I added some seo tags like described in the readme, but seo checker websites tell me, that there is no title tag for example.
I added the title tag like this:

`meta.ogTitle(ogTitle: "my title");`

How does this package handle the fact that the flutter environment needs some time to load and how does it handle dynamic content?

Cheers!

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for your interest Tim, I am still working on SSR and the work not completed yet as mentioned before to make new out of the box solution, thanks again..

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Now the support only for JS DOM not SSR...
