### ISSUE TITLE
About dynamic meta tags for SEO

### ISSUE THREAD

**Issue by Batres35** [Eng-Mouaz-M-AlShahmeh/meta_seo#15]
I'm developing a web application in Flutter Web and I just encountered the issue of meta tags. I realize there's a significant limitation in this framework for their implementation.

My intention with this application is to display certain dynamic content on the page based on an asynchronously queried database, use the same information in the meta tags, and have this information usable by other services (Facebook, WhatsApp, Twitter).

Is it currently possible to achieve this with this library?
In case it's not, what alternatives are available without having to rewrite the entire project in another framework?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for your interest Batres, I am still working on SSR and the work not completed yet as mentioned before to make new out of the box solution, thanks again..
