### ISSUE TITLE
Small feature requests, option to update title tag

### ISSUE THREAD

**Issue by MominRaza** [Eng-Mouaz-M-AlShahmeh/meta_seo#17]
Add a way to update `<title>` tag in `<head>`

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Welcome @MominRaza . Thanks for your interest, this feature already exists in Flutter by default to updating the title tag by JS dome, but if you want to add it by SSR, this idea is under development and not completed yet as mentioned before. Thanks again,
