### ISSUE TITLE
Using async data for meta while using GoRouter

### ISSUE THREAD

**Issue by guplem** [Eng-Mouaz-M-AlShahmeh/meta_seo#2]
_First: thanks for developing this package! It is surprising that something like this is missing from Flutter._

I am trying to build an ecommerce web app. The routing (using GoRouter) to the page of the product is something like "product/:id".

In your example of how to use meta_seo with GoRouter you hard-code the meta information. However, I do not have access to the meta information at the moment you suggest we add the meta info.  That information would be loaded within the page, after fetching it from the API using the product ID.

Would it be OK to define the meta object and add it once the API response with the product data is received?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Need some code snippets to understand you.

**Comment by guplem** [comment]
Sure!

I am talking about setting up the metadata after fetching the data of the product, since I don't know it beforehand.

Something like this:
  ```
fetchProductData(string id) async {
    http.get(Uri.parse('https://example.com/api/v1/products/$id'))
        .then((response) {
          // Define MetaSEO object with optional needed attributes
          MetaSEO meta = MetaSEO(
              ogTitle: response.name,
              description: response.description,
              keywords: response.tags
          );

          // add meta seo data for web app
          meta.seoOGTitle();
          meta.seoDescription();
          meta.seoKeywords();
        };
    }
```

Is this ok? 
Isn't metadata linked to a specific URL? How would it know it?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Good question. Yes just wrap the MetaSEO into GoRouter builder with FutureBuilder.

Example:
GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {

        return FutureBuilder(
          initialData: 0,
          future: Future.delayed(const Duration(seconds: 2), () {
            // TODO:: Define MetaSEO object with optional needed attributes
            MetaSEO meta = MetaSEO(
                author: 'Eng Mouaz M AlShahmeh',
                description: 'First Screen',
                keywords: 'Flutter, Dart, SEO, Meta, Web, First Screen');

            // TODO:: add meta seo data for web app
            meta.seoAuthor();
            meta.seoDescription();
            meta.seoKeywords();

            return 1;
          }),
            builder: (context, snapshot) {
            if(snapshot.data == 1) {
              return const FirstScreen();
            } else {
              return const LoadingScreen();
            }
        });
      },
    )

Thanks,

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Or like this 
<img width="882" alt="Screenshot 2022-12-15 at 1 19 21 PM" src="https://user-images.githubusercontent.com/86870601/207835140-346646bf-c63f-4b9a-8b5e-ee8a785640ab.png">

**Comment by guplem** [comment]
> Yes just wrap the MetaSEO into GoRouter builder with FutureBuilder.


Can you please explain why this is necessary? 
I'd rather not wrap a full page with future builder (for architectural reasons). I'd rather initialize the page and, in that page, do the loading.
Is there an issue if I use the same approach but not directly inside the GoRoute method?

**Comment by guplem** [comment]
> I'd rather initialize the page and, in that page, do the loading.

I achieved it doing it this way (full page code):

```
import 'package:flutter/material.dart';
import 'package:meta_seo/meta_seo.dart';
import 'package:tunzaa_marketplace/custom_widgets/scaffold.dart';
import 'package:tunzaa_marketplace/custom_widgets/text.dart';
import 'package:tunzaa_marketplace/features/product/api.dart';
import 'package:tunzaa_marketplace/features/product/model.dart';
import 'dart:convert';

class ProductScreen extends StatefulWidget {
  final String id;
  final Product? product;

  const ProductScreen({Key? key, required this.id, this.product}) : super(key: key);

  @override
  State<ProductScreen> createState() => _ProductScreenState();
}

void setMetaSEO(FullyLoadedProduct fullyLoadedProduct) {
  // Define MetaSEO object with optional needed attributes
  MetaSEO meta = MetaSEO(
    ogImage: fullyLoadedProduct.coverImage,
    ogTitle: fullyLoadedProduct.name,
    description: fullyLoadedProduct.description,
    // TAGS// keywords: 'Flutter, Dart, SEO, Meta, Web',
  );

  // add meta seo data for web app
  meta.seoAuthor();
  meta.seoDescription();
  meta.seoKeywords();
}

class _ProductScreenState extends State<ProductScreen> {
  FullyLoadedProduct? fullyLoadedProduct;

  @override
  void initState() {
    if (widget.product != null) {
      fullyLoadedProduct = FullyLoadedProduct.fromBaseProduct(widget.product!);
      setMetaSEO(fullyLoadedProduct!);
    }
    if (widget.product == null || widget.product is Product) {
      ProductAPI.getProduct(widget.id).then((fetchedProduct) {
        setState(() {
          fullyLoadedProduct = fetchedProduct;
          setMetaSEO(fullyLoadedProduct!);
        });
      });
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ScaffoldCustom(
      appBar: AppBar(title: const Text('Product Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextCustom("Product ID '${widget.id}'"),
            TextCustom("Product JSON data '${jsonEncode(fullyLoadedProduct, toEncodable: (dynamic object) => object.toJson())}'"),
            TextCustom("Product Name: '${fullyLoadedProduct?.name}'"),
          ],
        ),
      ),
    );
  }
}

```
