### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by sgehrman** [Eng-Mouaz-M-AlShahmeh/meta_seo#20]
I get this when compiling --wasm

Unsupported operation: Cannot create MetaSEO without the package dart:html. Just wrap the MetaSEO with "if(kIsWeb) condition."

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for your interest @sgehrman. This package is compatible with runtime wasm, and will be rewarded additional points in a future version of the scoring model. Thanks again,

**Comment by sgehrman** [comment]
It compiles now, but just crashes when it runs.

main.dart.mjs:19 Unsupported operation: Cannot create MetaSEO without the package dart:html. Just wrap the MetaSEO with "if(kIsWeb) condition."
main.dart.mjs:19     at http://localhost:8080/main.dart.wasm:wasm-function[909]:0x1b67af
    at http://localhost:8080/main.dart.wasm:wasm-function[25060]:0x3a56d4
    at http://localhost:8080/main.dart.wasm:wasm-function[2466]:0x1daa09
    at http://localhost:8080/main.dart.wasm:wasm-function[1381]:0x1c0d80
    at http://localhost:8080/main.dart.wasm:wasm-function[25071]:0x3a5b78
    at http://localhost:8080/main.dart.wasm:wasm-function[1965]:0x1d08ec
    at http://localhost:8080/main.dart.wasm:wasm-function[1970]:0x1d0955
    at http://localhost:8080/main.dart.wasm:wasm-function[1204]:0x1bbf98
main.dart.wasm:0x1b7a2f Uncaught Exception {}
$func956 @ main.dart.wasm:0x1b7a2f
$func909 @ main.dart.wasm:0x1b67b2
$$invokeCallback @ main.dart.wasm:0x1b5604
(anonymous) @ main.dart.mjs:595Understand this errorAI
