### ISSUE TITLE
OG Tags

### ISSUE THREAD

**Issue by rlee1990** [Eng-Mouaz-M-AlShahmeh/meta_seo#4]
Is there anything special that needs to be done for OG social cards to work or is that not supported?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
All things described within the readme file of meta_seo package. Thanks,

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh the readme clearly didn't state anything help that is why I asked the question but this package did not work for og meta tags

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Give me screenshots..

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh screenshots of what? I followed the examples and all.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Is your web app published online or localhost

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh I published it online using firebase hosting

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Good you can use any Open Graph meta tag..

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh will it take time for it to work?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Give screen shots, so I can help you if you want..

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh  do you want screenshots or snippets of the code? Or do you want a screenshot of how it looks when using the url?

**Comment by rlee1990** [comment]
<img width="491" alt="Screenshot 2023-01-22 at 2 09 39 PM" src="https://user-images.githubusercontent.com/21372502/213935183-f9aa5571-bfd3-488e-8bb0-37422360e8be.png">
Here is how it looks when trying to use it in Facebook

**Comment by rlee1990** [comment]
![Screenshot 2023-01-22 at 2 10 40 PM](https://user-images.githubusercontent.com/21372502/213935208-fcffe455-3e6b-4b69-9b8e-5f4bf0346345.png)
The code in my router
and the HTML from the browser:
<img width="537" alt="Screenshot 2023-01-22 at 2 11 34 PM" src="https://user-images.githubusercontent.com/21372502/213935245-4c80be64-d87e-4d33-8f79-23052cb09f3c.png">

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Ok, what is the problem.. it is running will?!

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
refer this url maybe it is helpful:
https://ogp.me

**Comment by rlee1990** [comment]
<img width="494" alt="Screenshot 2023-01-22 at 2 21 17 PM" src="https://user-images.githubusercontent.com/21372502/213935727-c4d64505-cd36-4031-8038-71cf49dd5134.png">

This is the issue. The above image shows how a url with meta tags should display vs how it did for us.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
If any meta is not listed. Simply you can add by cal the method [seoMetaPropertyContent](https://pub.dev/documentation/meta_seo/latest/web_meta_seo/WebMetaSEO/seoMetaPropertyContent.html)([String](https://api.dart.dev/stable/2.18.7/dart-core/String-class.html) metaProperty, [String](https://api.dart.dev/stable/2.18.7/dart-core/String-class.html) metaPropertyContent) → void ... Which is defined for any OG meta tags, Thanks,

**Comment by rlee1990** [comment]
Let me try a few things Ill let you know what happens thanks.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks,

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh So I used the Facebook debugger and a get the below error.
I tried using the seoMetaPropertyContent option and using the seoOGImage and tried both together nothing works
<img width="1047" alt="Screenshot 2023-01-22 at 2 52 45 PM" src="https://user-images.githubusercontent.com/21372502/213937276-5e5a1446-5ef7-4e68-9ae6-4abe1329ffce.png">

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Yes if [String](https://api.dart.dev/stable/2.18.7/dart-core/String-class.html) metaProperty, duplicated. Just the package delete the first one and replaced by the new.

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh it wasn't duplicated. Im stating I tried each option and got the same error then I tried adding them both and got the same error.
Something isn't right when it comes to using the og:image option

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Give me screenshots..

**Comment by rlee1990** [comment]
I sent screenshots already
@Eng-Mouaz-M-AlShahmeh

**Comment by rlee1990** [comment]
![Screenshot 2023-01-22 at 3 54 06 PM](https://user-images.githubusercontent.com/21372502/213939896-4f7af757-35a5-49ff-9786-b4229745a067.png)
<img width="568" alt="Screenshot 2023-01-22 at 3 54 53 PM" src="https://user-images.githubusercontent.com/21372502/213939949-d5f18df7-9791-4021-bf45-7311214ddf13.png">

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
The image is not exist on this link. Every thing other is done correct,

The image: ![image](https://jpvlhqughblujgeofyf.supabase.co/storage/vl/object/public/site-files/IMG_0007.jpeg)

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
https://jpvlhqughblujgeofyf.supabase.co/storage/vl/object/public/site-files/IMG_0007.jpeg

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Just try any online image.

**Comment by rlee1990** [comment]
Thanks thats odd it was working let me check on this.

**Comment by rlee1990** [comment]
[test](https://jpvlhqugxhblujqeofyf.supabase.co/storage/v1/object/public/site-files/IMG_0007.jpeg)

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh its not the image url 
I tried this one and got the same issue.
[https://i.picsum.photos/id/130/200/300.jpg?hmac=ax-dkx2e5CJww9f5IfH-mUHr_9eNBKUNGHcA46-0oB0](https://i.picsum.photos/id/130/200/300.jpg?hmac=ax-dkx2e5CJww9f5IfH-mUHr_9eNBKUNGHcA46-0oB0)

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh So I did a test with the same values but just adding meta tags directly to the html file like below and that works. So there is something within the package causing this.
```
<meta property="og:title" content='Rome Site'>
<meta property="og:site_name" content="Thee Rome'N'Way">
<meta property="og:url" content='https://romekitchen-e8020--ogtest-d9i39khd.web.app'>
<meta property="og:description" content='This is the menu page'>
<meta property="og:type" content='website'>
<meta property="og:image" content='https://jpvlhqugxhblujqeofyf.supabase.co/storage/v1/object/public/site-files/IMG_0007.jpeg'>
```

**Comment by rlee1990** [comment]
@Eng-Mouaz-M-AlShahmeh any updates?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Maybe with documentation not the code of package for this issue, because it is running well and I tested for OG image. Thanks,

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Just you must be in live server not in local host to see the results of sharing links..

**Comment by rlee1990** [comment]
I wasn't using local host I uploaded it to firebase hosting. It's fine I decided to use nextjs

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Not the image but all the flutter website,

**Comment by rlee1990** [comment]
Correct I ran flutter build for the web app and uploaded it to firebase hosting

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Ok,

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
I update the documentation of the package.

**Comment by cedvdb** [comment]
The `og:images` tag must be present in the HTML when the bot receives it as it will not execute javascript / flutter.


This package won't work for this use case, which is also what I'm researching here.
