### ISSUE TITLE
Open Graph - Sharing Debugger into Meta for Developers

### ISSUE THREAD

**Issue by mviniciuscorrea** [Eng-Mouaz-M-AlShahmeh/meta_seo#6]
i'm work in a company and we website is flutter web. I'm try use your package to add tags open graph/twitter into each page (home, products..). Can you help me please?

When i see the elements page, the package add the tags OG.. so its working :)

![3](https://user-images.githubusercontent.com/123556973/225395131-f15b3ad1-9671-41a8-8eda-4a9068e14c29.png)

But when past link to [(Sharing Debugger into Meta for Developers )](https://developers.facebook.com/tools/debug/) or [(Card Validator 
 on Twitter)](https://cards-dev.twitter.com/validator), he get initial default index from flutter and dont loaded the properties OG, so showing error:

![1](https://user-images.githubusercontent.com/123556973/225392618-5ce07f42-05c4-4f5f-81de-dadf307a69b7.png)

if click in Scraped URL to see exactly what scrap url, dont show the tags OG

![2](https://user-images.githubusercontent.com/123556973/225393769-364f01e4-837c-4bbb-ab79-685539a0bc54.png)

Do you can help me with this? Exists any method to work?
Thank you and best regards

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
@mviniciuscorrea  Thanks for the issue, refer the latest version on pub.dev. the issue is solved with support of data react helmet. 
Thanks,

**Comment by marcuscorreasmash** [comment]
Sorry, but dont work into version 3.0.2

I'm added all tags but into Facebook debugger dont loading the informations

the page:
![image](https://user-images.githubusercontent.com/123556973/225771801-848ff458-cb04-4fdf-8e7a-55b30d52ec52.png)

Facebook debugger:
![image](https://user-images.githubusercontent.com/123556973/225772012-88d3bbf0-ddae-4eb9-a11a-ed137e467ac9.png)

if you want see the page, this is my url: https://marcuscorreasmash.github.io/seo/

This page is same example into pud.dev (https://github.com/Eng-Mouaz-M-AlShahmeh/meta_seo_with_go_router_example)

I'm read the issue #4 and this problem exactly man report, but he decided to use nextjs

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Welcome the latest version is 3.0.4, the problem maybe from many reasons:
- og:url is not correct
- It's a bug on Facebook end, just refreshing the sharing debugger 
- or just clear cache from browser you use
- or another bug I fixed with the release of 3.0.4.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Yes nextJS is fantastic especially with express,
All of examples are updated, let me know if it is running well now.
:)

**Comment by Lucianossr** [comment]
i have same problem descrit by @mviniciuscorrea 

What solution was applied?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for interest, I am working now on the best solution for supporting SSR (Server Side Rendering), to make changes on View Source Page, which not depend on JS DOM.
So be patient,
Thanks again,

**Comment by jeanbatm** [comment]
I have exactly the same problem. Tags are present in the element page but it is not detected in facebook debugger.
