### ISSUE TITLE
I've tried to use the package

### ISSUE THREAD

**Issue by batataw** [Eng-Mouaz-M-AlShahmeh/meta_seo#7]
Another exception was thrown: Unexpected null value.
Another exception was thrown: NoSuchMethodError: 'seoOpenGraphJS'

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for your interest [batataw](https://github.com/batataw). Refer last issues and refer configuration details in [pub.dev](https://pub.dev/packages/meta_seo) if you want. Or read me file.
