### ISSUE TITLE
meta tags not displayed

### ISSUE THREAD

**Issue by AbanoubWagih94** [Eng-Mouaz-M-AlShahmeh/meta_seo#8]
hi i am trying to use this package for seo
and i follow what u say but no thing appear when inspect my page

**Comment by AbanoubWagih94** [comment]
solved

**Comment by AbanoubWagih94** [comment]
i was thought that that package not working but i was wrong

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Ok, Thanks..

**Comment by mishatron** [comment]
I have the same issue. I even downloaded your example, launched, looked at code source - and I dont see any meta tags there
