### ISSUE TITLE
Getting some Insights

### ISSUE THREAD

**Issue by ben55j** [Eng-Mouaz-M-AlShahmeh/meta_seo#9]
Hello Mouaz, 

Thank you for this great package !
Since I have facing indexation issues on my Flutter website, I would like to get some of your Insights / advices regarding this package.  

I have a few questions:
- Is the technique used in this package considered similar to cloaking in the eyes of Google?
- Have you personally achieved successful indexing of pages on a website using this plugin?
- Do you have any examples of Flutter websites with multiple pages successfully indexed by Google?

Here the kind of URLs I am trying to get indexed. It's already using your package: https://www.servicesadom.com/pro/yasmine. 

I would greatly appreciate some of your advices on this Google indexation topics for Flutter Websites. 

Thank you,
Benjamin

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for your interest @ben55j. We are working now on smart and out of the box solution to support SSR (Server Side Rendering) solution to support "View Source Page" functionality. It may take a while because it is big issue.
